name: easyviewer
description: "App to download YouTube videos"
publish_to: 'none'
version: 3.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.5.1
  flutter_window_close: ^1.3.0
  intl: ^0.20.2
  path: ^1.9.1
  url_launcher: ^6.3.2
  file_picker: ^10.3.3
  path_provider: ^2.1.5
  http: ^1.5.0
  youtube_explode_dart: ^3.0.3
  flutter_localizations:
    sdk: flutter
  pub_semver: ^2.2.0
  ffmpeg_kit_flutter_minimal: ^6.0.8
  shared_preferences: ^2.5.3
  logkeeper: ^1.1.0+2
  fluikit:
    git:
      url: https://github.com/RaulCatalinas/Fluikit.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter-latin-400-normal.ttf
          weight: 400
          style: normal

flutter_launcher_icons:
  image_path: "assets/icon.png"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
  linux:
    generate: true